//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ThreadPool {
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://tempuri.org")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.ThreadPool.Request.RequestStatusType RequestStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HandledTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RequestString {
            get {
                return this.RequestStringField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestStringField, value) != true)) {
                    this.RequestStringField = value;
                    this.RaisePropertyChanged("RequestString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public Client.ThreadPool.Request.RequestStatusType RequestStatus {
            get {
                return this.RequestStatusField;
            }
            set {
                if ((this.RequestStatusField.Equals(value) != true)) {
                    this.RequestStatusField = value;
                    this.RaisePropertyChanged("RequestStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AddedTime {
            get {
                return this.AddedTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddedTimeField, value) != true)) {
                    this.AddedTimeField = value;
                    this.RaisePropertyChanged("AddedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HandledTime {
            get {
                return this.HandledTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.HandledTimeField, value) != true)) {
                    this.HandledTimeField = value;
                    this.RaisePropertyChanged("HandledTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ErrorData {
            get {
                return this.ErrorDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDataField, value) != true)) {
                    this.ErrorDataField = value;
                    this.RaisePropertyChanged("ErrorData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Request.RequestStatusType", Namespace="http://tempuri.org")]
        public enum RequestStatusType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            WAITING = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            IN_STACK = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            RUNNING = 2,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            READY = 3,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            READY_WITH_ERROR = 4,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="ThreadPool.ThreadPoolServiceSoap")]
    public interface ThreadPoolServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем GetFullRequestResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolService.GetFullRequest", ReplyAction="*")]
        Client.ThreadPool.GetFullRequestResponse GetFullRequest(Client.ThreadPool.GetFullRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolService.GetFullRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ThreadPool.GetFullRequestResponse> GetFullRequestAsync(Client.ThreadPool.GetFullRequestRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetProcTaskDataResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolService.GetProcTaskData", ReplyAction="*")]
        Client.ThreadPool.GetProcTaskDataResponse GetProcTaskData(Client.ThreadPool.GetProcTaskDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolService.GetProcTaskData", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ThreadPool.GetProcTaskDataResponse> GetProcTaskDataAsync(Client.ThreadPool.GetProcTaskDataRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем ReqString из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolService.GetRId", ReplyAction="*")]
        Client.ThreadPool.GetRIdResponse GetRId(Client.ThreadPool.GetRIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolService.GetRId", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ThreadPool.GetRIdResponse> GetRIdAsync(Client.ThreadPool.GetRIdRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем ResultResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolService.Result", ReplyAction="*")]
        Client.ThreadPool.ResultResponse Result(Client.ThreadPool.ResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolService.Result", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ThreadPool.ResultResponse> ResultAsync(Client.ThreadPool.ResultRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем StatusResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolService.Status", ReplyAction="*")]
        Client.ThreadPool.StatusResponse Status(Client.ThreadPool.StatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ThreadPool.ThreadPoolService.Status", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ThreadPool.StatusResponse> StatusAsync(Client.ThreadPool.StatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFullRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFullRequest", Namespace="http://tempuri.org", Order=0)]
        public Client.ThreadPool.GetFullRequestRequestBody Body;
        
        public GetFullRequestRequest() {
        }
        
        public GetFullRequestRequest(Client.ThreadPool.GetFullRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetFullRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public GetFullRequestRequestBody() {
        }
        
        public GetFullRequestRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFullRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFullRequestResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ThreadPool.GetFullRequestResponseBody Body;
        
        public GetFullRequestResponse() {
        }
        
        public GetFullRequestResponse(Client.ThreadPool.GetFullRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetFullRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ThreadPool.Request GetFullRequestResult;
        
        public GetFullRequestResponseBody() {
        }
        
        public GetFullRequestResponseBody(Client.ThreadPool.Request GetFullRequestResult) {
            this.GetFullRequestResult = GetFullRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcTaskDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcTaskData", Namespace="http://tempuri.org", Order=0)]
        public Client.ThreadPool.GetProcTaskDataRequestBody Body;
        
        public GetProcTaskDataRequest() {
        }
        
        public GetProcTaskDataRequest(Client.ThreadPool.GetProcTaskDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProcTaskDataRequestBody {
        
        public GetProcTaskDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProcTaskDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProcTaskDataResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ThreadPool.GetProcTaskDataResponseBody Body;
        
        public GetProcTaskDataResponse() {
        }
        
        public GetProcTaskDataResponse(Client.ThreadPool.GetProcTaskDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetProcTaskDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProcTaskDataResult;
        
        public GetProcTaskDataResponseBody() {
        }
        
        public GetProcTaskDataResponseBody(string GetProcTaskDataResult) {
            this.GetProcTaskDataResult = GetProcTaskDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRId", Namespace="http://tempuri.org", Order=0)]
        public Client.ThreadPool.GetRIdRequestBody Body;
        
        public GetRIdRequest() {
        }
        
        public GetRIdRequest(Client.ThreadPool.GetRIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetRIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReqString;
        
        public GetRIdRequestBody() {
        }
        
        public GetRIdRequestBody(string ReqString) {
            this.ReqString = ReqString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRIdResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ThreadPool.GetRIdResponseBody Body;
        
        public GetRIdResponse() {
        }
        
        public GetRIdResponse(Client.ThreadPool.GetRIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetRIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRIdResult;
        
        public GetRIdResponseBody() {
        }
        
        public GetRIdResponseBody(string GetRIdResult) {
            this.GetRIdResult = GetRIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Result", Namespace="http://tempuri.org", Order=0)]
        public Client.ThreadPool.ResultRequestBody Body;
        
        public ResultRequest() {
        }
        
        public ResultRequest(Client.ThreadPool.ResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class ResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public ResultRequestBody() {
        }
        
        public ResultRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ThreadPool.ResultResponseBody Body;
        
        public ResultResponse() {
        }
        
        public ResultResponse(Client.ThreadPool.ResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class ResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResultResult;
        
        public ResultResponseBody() {
        }
        
        public ResultResponseBody(string ResultResult) {
            this.ResultResult = ResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Status", Namespace="http://tempuri.org", Order=0)]
        public Client.ThreadPool.StatusRequestBody Body;
        
        public StatusRequest() {
        }
        
        public StatusRequest(Client.ThreadPool.StatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class StatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public StatusRequestBody() {
        }
        
        public StatusRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ThreadPool.StatusResponseBody Body;
        
        public StatusResponse() {
        }
        
        public StatusResponse(Client.ThreadPool.StatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class StatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatusResult;
        
        public StatusResponseBody() {
        }
        
        public StatusResponseBody(string StatusResult) {
            this.StatusResult = StatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ThreadPoolServiceSoapChannel : Client.ThreadPool.ThreadPoolServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThreadPoolServiceSoapClient : System.ServiceModel.ClientBase<Client.ThreadPool.ThreadPoolServiceSoap>, Client.ThreadPool.ThreadPoolServiceSoap {
        
        public ThreadPoolServiceSoapClient() {
        }
        
        public ThreadPoolServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThreadPoolServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThreadPoolServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThreadPoolServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ThreadPool.GetFullRequestResponse Client.ThreadPool.ThreadPoolServiceSoap.GetFullRequest(Client.ThreadPool.GetFullRequestRequest request) {
            return base.Channel.GetFullRequest(request);
        }
        
        public Client.ThreadPool.Request GetFullRequest(long id) {
            Client.ThreadPool.GetFullRequestRequest inValue = new Client.ThreadPool.GetFullRequestRequest();
            inValue.Body = new Client.ThreadPool.GetFullRequestRequestBody();
            inValue.Body.id = id;
            Client.ThreadPool.GetFullRequestResponse retVal = ((Client.ThreadPool.ThreadPoolServiceSoap)(this)).GetFullRequest(inValue);
            return retVal.Body.GetFullRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ThreadPool.GetFullRequestResponse> Client.ThreadPool.ThreadPoolServiceSoap.GetFullRequestAsync(Client.ThreadPool.GetFullRequestRequest request) {
            return base.Channel.GetFullRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ThreadPool.GetFullRequestResponse> GetFullRequestAsync(long id) {
            Client.ThreadPool.GetFullRequestRequest inValue = new Client.ThreadPool.GetFullRequestRequest();
            inValue.Body = new Client.ThreadPool.GetFullRequestRequestBody();
            inValue.Body.id = id;
            return ((Client.ThreadPool.ThreadPoolServiceSoap)(this)).GetFullRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ThreadPool.GetProcTaskDataResponse Client.ThreadPool.ThreadPoolServiceSoap.GetProcTaskData(Client.ThreadPool.GetProcTaskDataRequest request) {
            return base.Channel.GetProcTaskData(request);
        }
        
        public string GetProcTaskData() {
            Client.ThreadPool.GetProcTaskDataRequest inValue = new Client.ThreadPool.GetProcTaskDataRequest();
            inValue.Body = new Client.ThreadPool.GetProcTaskDataRequestBody();
            Client.ThreadPool.GetProcTaskDataResponse retVal = ((Client.ThreadPool.ThreadPoolServiceSoap)(this)).GetProcTaskData(inValue);
            return retVal.Body.GetProcTaskDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ThreadPool.GetProcTaskDataResponse> Client.ThreadPool.ThreadPoolServiceSoap.GetProcTaskDataAsync(Client.ThreadPool.GetProcTaskDataRequest request) {
            return base.Channel.GetProcTaskDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ThreadPool.GetProcTaskDataResponse> GetProcTaskDataAsync() {
            Client.ThreadPool.GetProcTaskDataRequest inValue = new Client.ThreadPool.GetProcTaskDataRequest();
            inValue.Body = new Client.ThreadPool.GetProcTaskDataRequestBody();
            return ((Client.ThreadPool.ThreadPoolServiceSoap)(this)).GetProcTaskDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ThreadPool.GetRIdResponse Client.ThreadPool.ThreadPoolServiceSoap.GetRId(Client.ThreadPool.GetRIdRequest request) {
            return base.Channel.GetRId(request);
        }
        
        public string GetRId(string ReqString) {
            Client.ThreadPool.GetRIdRequest inValue = new Client.ThreadPool.GetRIdRequest();
            inValue.Body = new Client.ThreadPool.GetRIdRequestBody();
            inValue.Body.ReqString = ReqString;
            Client.ThreadPool.GetRIdResponse retVal = ((Client.ThreadPool.ThreadPoolServiceSoap)(this)).GetRId(inValue);
            return retVal.Body.GetRIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ThreadPool.GetRIdResponse> Client.ThreadPool.ThreadPoolServiceSoap.GetRIdAsync(Client.ThreadPool.GetRIdRequest request) {
            return base.Channel.GetRIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ThreadPool.GetRIdResponse> GetRIdAsync(string ReqString) {
            Client.ThreadPool.GetRIdRequest inValue = new Client.ThreadPool.GetRIdRequest();
            inValue.Body = new Client.ThreadPool.GetRIdRequestBody();
            inValue.Body.ReqString = ReqString;
            return ((Client.ThreadPool.ThreadPoolServiceSoap)(this)).GetRIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ThreadPool.ResultResponse Client.ThreadPool.ThreadPoolServiceSoap.Result(Client.ThreadPool.ResultRequest request) {
            return base.Channel.Result(request);
        }
        
        public string Result(long id) {
            Client.ThreadPool.ResultRequest inValue = new Client.ThreadPool.ResultRequest();
            inValue.Body = new Client.ThreadPool.ResultRequestBody();
            inValue.Body.id = id;
            Client.ThreadPool.ResultResponse retVal = ((Client.ThreadPool.ThreadPoolServiceSoap)(this)).Result(inValue);
            return retVal.Body.ResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ThreadPool.ResultResponse> Client.ThreadPool.ThreadPoolServiceSoap.ResultAsync(Client.ThreadPool.ResultRequest request) {
            return base.Channel.ResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ThreadPool.ResultResponse> ResultAsync(long id) {
            Client.ThreadPool.ResultRequest inValue = new Client.ThreadPool.ResultRequest();
            inValue.Body = new Client.ThreadPool.ResultRequestBody();
            inValue.Body.id = id;
            return ((Client.ThreadPool.ThreadPoolServiceSoap)(this)).ResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ThreadPool.StatusResponse Client.ThreadPool.ThreadPoolServiceSoap.Status(Client.ThreadPool.StatusRequest request) {
            return base.Channel.Status(request);
        }
        
        public string Status(long id) {
            Client.ThreadPool.StatusRequest inValue = new Client.ThreadPool.StatusRequest();
            inValue.Body = new Client.ThreadPool.StatusRequestBody();
            inValue.Body.id = id;
            Client.ThreadPool.StatusResponse retVal = ((Client.ThreadPool.ThreadPoolServiceSoap)(this)).Status(inValue);
            return retVal.Body.StatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ThreadPool.StatusResponse> Client.ThreadPool.ThreadPoolServiceSoap.StatusAsync(Client.ThreadPool.StatusRequest request) {
            return base.Channel.StatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ThreadPool.StatusResponse> StatusAsync(long id) {
            Client.ThreadPool.StatusRequest inValue = new Client.ThreadPool.StatusRequest();
            inValue.Body = new Client.ThreadPool.StatusRequestBody();
            inValue.Body.id = id;
            return ((Client.ThreadPool.ThreadPoolServiceSoap)(this)).StatusAsync(inValue);
        }
    }
}
