//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="ServiceReference1.SingleServiceSoap")]
    public interface SingleServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем ReqString из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.GetRId", ReplyAction="*")]
        Client.ServiceReference1.GetRIdResponse GetRId(Client.ServiceReference1.GetRIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.GetRId", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetRIdResponse> GetRIdAsync(Client.ServiceReference1.GetRIdRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем JobStateResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.JobState", ReplyAction="*")]
        Client.ServiceReference1.JobStateResponse JobState(Client.ServiceReference1.JobStateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.JobState", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.JobStateResponse> JobStateAsync(Client.ServiceReference1.JobStateRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем ResultResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.Result", ReplyAction="*")]
        Client.ServiceReference1.ResultResponse Result(Client.ServiceReference1.ResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.Result", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.ResultResponse> ResultAsync(Client.ServiceReference1.ResultRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем StartHandlingResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.StartHandling", ReplyAction="*")]
        Client.ServiceReference1.StartHandlingResponse StartHandling(Client.ServiceReference1.StartHandlingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.StartHandling", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.StartHandlingResponse> StartHandlingAsync(Client.ServiceReference1.StartHandlingRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем StatusResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.Status", ReplyAction="*")]
        Client.ServiceReference1.StatusResponse Status(Client.ServiceReference1.StatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.Status", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.StatusResponse> StatusAsync(Client.ServiceReference1.StatusRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем TestResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.Test", ReplyAction="*")]
        Client.ServiceReference1.TestResponse Test(Client.ServiceReference1.TestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP2.SingleService.Test", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.ServiceReference1.TestResponse> TestAsync(Client.ServiceReference1.TestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRId", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.GetRIdRequestBody Body;
        
        public GetRIdRequest() {
        }
        
        public GetRIdRequest(Client.ServiceReference1.GetRIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetRIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReqString;
        
        public GetRIdRequestBody() {
        }
        
        public GetRIdRequestBody(string ReqString) {
            this.ReqString = ReqString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRIdResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.GetRIdResponseBody Body;
        
        public GetRIdResponse() {
        }
        
        public GetRIdResponse(Client.ServiceReference1.GetRIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetRIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRIdResult;
        
        public GetRIdResponseBody() {
        }
        
        public GetRIdResponseBody(string GetRIdResult) {
            this.GetRIdResult = GetRIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JobStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JobState", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.JobStateRequestBody Body;
        
        public JobStateRequest() {
        }
        
        public JobStateRequest(Client.ServiceReference1.JobStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class JobStateRequestBody {
        
        public JobStateRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class JobStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="JobStateResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.JobStateResponseBody Body;
        
        public JobStateResponse() {
        }
        
        public JobStateResponse(Client.ServiceReference1.JobStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class JobStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string JobStateResult;
        
        public JobStateResponseBody() {
        }
        
        public JobStateResponseBody(string JobStateResult) {
            this.JobStateResult = JobStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Result", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.ResultRequestBody Body;
        
        public ResultRequest() {
        }
        
        public ResultRequest(Client.ServiceReference1.ResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class ResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public ResultRequestBody() {
        }
        
        public ResultRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.ResultResponseBody Body;
        
        public ResultResponse() {
        }
        
        public ResultResponse(Client.ServiceReference1.ResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class ResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResultResult;
        
        public ResultResponseBody() {
        }
        
        public ResultResponseBody(string ResultResult) {
            this.ResultResult = ResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartHandlingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartHandling", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.StartHandlingRequestBody Body;
        
        public StartHandlingRequest() {
        }
        
        public StartHandlingRequest(Client.ServiceReference1.StartHandlingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StartHandlingRequestBody {
        
        public StartHandlingRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StartHandlingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StartHandlingResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.StartHandlingResponseBody Body;
        
        public StartHandlingResponse() {
        }
        
        public StartHandlingResponse(Client.ServiceReference1.StartHandlingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class StartHandlingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StartHandlingResult;
        
        public StartHandlingResponseBody() {
        }
        
        public StartHandlingResponseBody(string StartHandlingResult) {
            this.StartHandlingResult = StartHandlingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Status", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.StatusRequestBody Body;
        
        public StatusRequest() {
        }
        
        public StatusRequest(Client.ServiceReference1.StatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class StatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public StatusRequestBody() {
        }
        
        public StatusRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.StatusResponseBody Body;
        
        public StatusResponse() {
        }
        
        public StatusResponse(Client.ServiceReference1.StatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class StatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatusResult;
        
        public StatusResponseBody() {
        }
        
        public StatusResponseBody(string StatusResult) {
            this.StatusResult = StatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Test", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.TestRequestBody Body;
        
        public TestRequest() {
        }
        
        public TestRequest(Client.ServiceReference1.TestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TestRequestBody {
        
        public TestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TestResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.ServiceReference1.TestResponseBody Body;
        
        public TestResponse() {
        }
        
        public TestResponse(Client.ServiceReference1.TestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class TestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TestResult;
        
        public TestResponseBody() {
        }
        
        public TestResponseBody(string TestResult) {
            this.TestResult = TestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SingleServiceSoapChannel : Client.ServiceReference1.SingleServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SingleServiceSoapClient : System.ServiceModel.ClientBase<Client.ServiceReference1.SingleServiceSoap>, Client.ServiceReference1.SingleServiceSoap {
        
        public SingleServiceSoapClient() {
        }
        
        public SingleServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SingleServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SingleServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.GetRIdResponse Client.ServiceReference1.SingleServiceSoap.GetRId(Client.ServiceReference1.GetRIdRequest request) {
            return base.Channel.GetRId(request);
        }
        
        public string GetRId(string ReqString) {
            Client.ServiceReference1.GetRIdRequest inValue = new Client.ServiceReference1.GetRIdRequest();
            inValue.Body = new Client.ServiceReference1.GetRIdRequestBody();
            inValue.Body.ReqString = ReqString;
            Client.ServiceReference1.GetRIdResponse retVal = ((Client.ServiceReference1.SingleServiceSoap)(this)).GetRId(inValue);
            return retVal.Body.GetRIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.GetRIdResponse> Client.ServiceReference1.SingleServiceSoap.GetRIdAsync(Client.ServiceReference1.GetRIdRequest request) {
            return base.Channel.GetRIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.GetRIdResponse> GetRIdAsync(string ReqString) {
            Client.ServiceReference1.GetRIdRequest inValue = new Client.ServiceReference1.GetRIdRequest();
            inValue.Body = new Client.ServiceReference1.GetRIdRequestBody();
            inValue.Body.ReqString = ReqString;
            return ((Client.ServiceReference1.SingleServiceSoap)(this)).GetRIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.JobStateResponse Client.ServiceReference1.SingleServiceSoap.JobState(Client.ServiceReference1.JobStateRequest request) {
            return base.Channel.JobState(request);
        }
        
        public string JobState() {
            Client.ServiceReference1.JobStateRequest inValue = new Client.ServiceReference1.JobStateRequest();
            inValue.Body = new Client.ServiceReference1.JobStateRequestBody();
            Client.ServiceReference1.JobStateResponse retVal = ((Client.ServiceReference1.SingleServiceSoap)(this)).JobState(inValue);
            return retVal.Body.JobStateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.JobStateResponse> Client.ServiceReference1.SingleServiceSoap.JobStateAsync(Client.ServiceReference1.JobStateRequest request) {
            return base.Channel.JobStateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.JobStateResponse> JobStateAsync() {
            Client.ServiceReference1.JobStateRequest inValue = new Client.ServiceReference1.JobStateRequest();
            inValue.Body = new Client.ServiceReference1.JobStateRequestBody();
            return ((Client.ServiceReference1.SingleServiceSoap)(this)).JobStateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.ResultResponse Client.ServiceReference1.SingleServiceSoap.Result(Client.ServiceReference1.ResultRequest request) {
            return base.Channel.Result(request);
        }
        
        public string Result(long id) {
            Client.ServiceReference1.ResultRequest inValue = new Client.ServiceReference1.ResultRequest();
            inValue.Body = new Client.ServiceReference1.ResultRequestBody();
            inValue.Body.id = id;
            Client.ServiceReference1.ResultResponse retVal = ((Client.ServiceReference1.SingleServiceSoap)(this)).Result(inValue);
            return retVal.Body.ResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.ResultResponse> Client.ServiceReference1.SingleServiceSoap.ResultAsync(Client.ServiceReference1.ResultRequest request) {
            return base.Channel.ResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.ResultResponse> ResultAsync(long id) {
            Client.ServiceReference1.ResultRequest inValue = new Client.ServiceReference1.ResultRequest();
            inValue.Body = new Client.ServiceReference1.ResultRequestBody();
            inValue.Body.id = id;
            return ((Client.ServiceReference1.SingleServiceSoap)(this)).ResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.StartHandlingResponse Client.ServiceReference1.SingleServiceSoap.StartHandling(Client.ServiceReference1.StartHandlingRequest request) {
            return base.Channel.StartHandling(request);
        }
        
        public string StartHandling() {
            Client.ServiceReference1.StartHandlingRequest inValue = new Client.ServiceReference1.StartHandlingRequest();
            inValue.Body = new Client.ServiceReference1.StartHandlingRequestBody();
            Client.ServiceReference1.StartHandlingResponse retVal = ((Client.ServiceReference1.SingleServiceSoap)(this)).StartHandling(inValue);
            return retVal.Body.StartHandlingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.StartHandlingResponse> Client.ServiceReference1.SingleServiceSoap.StartHandlingAsync(Client.ServiceReference1.StartHandlingRequest request) {
            return base.Channel.StartHandlingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.StartHandlingResponse> StartHandlingAsync() {
            Client.ServiceReference1.StartHandlingRequest inValue = new Client.ServiceReference1.StartHandlingRequest();
            inValue.Body = new Client.ServiceReference1.StartHandlingRequestBody();
            return ((Client.ServiceReference1.SingleServiceSoap)(this)).StartHandlingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.StatusResponse Client.ServiceReference1.SingleServiceSoap.Status(Client.ServiceReference1.StatusRequest request) {
            return base.Channel.Status(request);
        }
        
        public string Status(long id) {
            Client.ServiceReference1.StatusRequest inValue = new Client.ServiceReference1.StatusRequest();
            inValue.Body = new Client.ServiceReference1.StatusRequestBody();
            inValue.Body.id = id;
            Client.ServiceReference1.StatusResponse retVal = ((Client.ServiceReference1.SingleServiceSoap)(this)).Status(inValue);
            return retVal.Body.StatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.StatusResponse> Client.ServiceReference1.SingleServiceSoap.StatusAsync(Client.ServiceReference1.StatusRequest request) {
            return base.Channel.StatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.StatusResponse> StatusAsync(long id) {
            Client.ServiceReference1.StatusRequest inValue = new Client.ServiceReference1.StatusRequest();
            inValue.Body = new Client.ServiceReference1.StatusRequestBody();
            inValue.Body.id = id;
            return ((Client.ServiceReference1.SingleServiceSoap)(this)).StatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.TestResponse Client.ServiceReference1.SingleServiceSoap.Test(Client.ServiceReference1.TestRequest request) {
            return base.Channel.Test(request);
        }
        
        public string Test() {
            Client.ServiceReference1.TestRequest inValue = new Client.ServiceReference1.TestRequest();
            inValue.Body = new Client.ServiceReference1.TestRequestBody();
            Client.ServiceReference1.TestResponse retVal = ((Client.ServiceReference1.SingleServiceSoap)(this)).Test(inValue);
            return retVal.Body.TestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.ServiceReference1.TestResponse> Client.ServiceReference1.SingleServiceSoap.TestAsync(Client.ServiceReference1.TestRequest request) {
            return base.Channel.TestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.ServiceReference1.TestResponse> TestAsync() {
            Client.ServiceReference1.TestRequest inValue = new Client.ServiceReference1.TestRequest();
            inValue.Body = new Client.ServiceReference1.TestRequestBody();
            return ((Client.ServiceReference1.SingleServiceSoap)(this)).TestAsync(inValue);
        }
    }
}
