//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.TP4 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="TP4.ThreadPoolSeviceSoap")]
    public interface ThreadPoolSeviceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем ReqString из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP4.ThreadPoolSevice.GetRId", ReplyAction="*")]
        Client.TP4.GetRIdResponse GetRId(Client.TP4.GetRIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP4.ThreadPoolSevice.GetRId", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.TP4.GetRIdResponse> GetRIdAsync(Client.TP4.GetRIdRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем ResultResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP4.ThreadPoolSevice.Result", ReplyAction="*")]
        Client.TP4.ResultResponse Result(Client.TP4.ResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP4.ThreadPoolSevice.Result", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.TP4.ResultResponse> ResultAsync(Client.TP4.ResultRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем StatusResult из пространства имен http://tempuri.org не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP4.ThreadPoolSevice.Status", ReplyAction="*")]
        Client.TP4.StatusResponse Status(Client.TP4.StatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TP4.ThreadPoolSevice.Status", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.TP4.StatusResponse> StatusAsync(Client.TP4.StatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRId", Namespace="http://tempuri.org", Order=0)]
        public Client.TP4.GetRIdRequestBody Body;
        
        public GetRIdRequest() {
        }
        
        public GetRIdRequest(Client.TP4.GetRIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetRIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReqString;
        
        public GetRIdRequestBody() {
        }
        
        public GetRIdRequestBody(string ReqString) {
            this.ReqString = ReqString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRIdResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.TP4.GetRIdResponseBody Body;
        
        public GetRIdResponse() {
        }
        
        public GetRIdResponse(Client.TP4.GetRIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetRIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRIdResult;
        
        public GetRIdResponseBody() {
        }
        
        public GetRIdResponseBody(string GetRIdResult) {
            this.GetRIdResult = GetRIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Result", Namespace="http://tempuri.org", Order=0)]
        public Client.TP4.ResultRequestBody Body;
        
        public ResultRequest() {
        }
        
        public ResultRequest(Client.TP4.ResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class ResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public ResultRequestBody() {
        }
        
        public ResultRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ResultResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.TP4.ResultResponseBody Body;
        
        public ResultResponse() {
        }
        
        public ResultResponse(Client.TP4.ResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class ResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ResultResult;
        
        public ResultResponseBody() {
        }
        
        public ResultResponseBody(string ResultResult) {
            this.ResultResult = ResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Status", Namespace="http://tempuri.org", Order=0)]
        public Client.TP4.StatusRequestBody Body;
        
        public StatusRequest() {
        }
        
        public StatusRequest(Client.TP4.StatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class StatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public StatusRequestBody() {
        }
        
        public StatusRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StatusResponse", Namespace="http://tempuri.org", Order=0)]
        public Client.TP4.StatusResponseBody Body;
        
        public StatusResponse() {
        }
        
        public StatusResponse(Client.TP4.StatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class StatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StatusResult;
        
        public StatusResponseBody() {
        }
        
        public StatusResponseBody(string StatusResult) {
            this.StatusResult = StatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ThreadPoolSeviceSoapChannel : Client.TP4.ThreadPoolSeviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ThreadPoolSeviceSoapClient : System.ServiceModel.ClientBase<Client.TP4.ThreadPoolSeviceSoap>, Client.TP4.ThreadPoolSeviceSoap {
        
        public ThreadPoolSeviceSoapClient() {
        }
        
        public ThreadPoolSeviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ThreadPoolSeviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThreadPoolSeviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ThreadPoolSeviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.TP4.GetRIdResponse Client.TP4.ThreadPoolSeviceSoap.GetRId(Client.TP4.GetRIdRequest request) {
            return base.Channel.GetRId(request);
        }
        
        public string GetRId(string ReqString) {
            Client.TP4.GetRIdRequest inValue = new Client.TP4.GetRIdRequest();
            inValue.Body = new Client.TP4.GetRIdRequestBody();
            inValue.Body.ReqString = ReqString;
            Client.TP4.GetRIdResponse retVal = ((Client.TP4.ThreadPoolSeviceSoap)(this)).GetRId(inValue);
            return retVal.Body.GetRIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.TP4.GetRIdResponse> Client.TP4.ThreadPoolSeviceSoap.GetRIdAsync(Client.TP4.GetRIdRequest request) {
            return base.Channel.GetRIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.TP4.GetRIdResponse> GetRIdAsync(string ReqString) {
            Client.TP4.GetRIdRequest inValue = new Client.TP4.GetRIdRequest();
            inValue.Body = new Client.TP4.GetRIdRequestBody();
            inValue.Body.ReqString = ReqString;
            return ((Client.TP4.ThreadPoolSeviceSoap)(this)).GetRIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.TP4.ResultResponse Client.TP4.ThreadPoolSeviceSoap.Result(Client.TP4.ResultRequest request) {
            return base.Channel.Result(request);
        }
        
        public string Result(long id) {
            Client.TP4.ResultRequest inValue = new Client.TP4.ResultRequest();
            inValue.Body = new Client.TP4.ResultRequestBody();
            inValue.Body.id = id;
            Client.TP4.ResultResponse retVal = ((Client.TP4.ThreadPoolSeviceSoap)(this)).Result(inValue);
            return retVal.Body.ResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.TP4.ResultResponse> Client.TP4.ThreadPoolSeviceSoap.ResultAsync(Client.TP4.ResultRequest request) {
            return base.Channel.ResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.TP4.ResultResponse> ResultAsync(long id) {
            Client.TP4.ResultRequest inValue = new Client.TP4.ResultRequest();
            inValue.Body = new Client.TP4.ResultRequestBody();
            inValue.Body.id = id;
            return ((Client.TP4.ThreadPoolSeviceSoap)(this)).ResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.TP4.StatusResponse Client.TP4.ThreadPoolSeviceSoap.Status(Client.TP4.StatusRequest request) {
            return base.Channel.Status(request);
        }
        
        public string Status(long id) {
            Client.TP4.StatusRequest inValue = new Client.TP4.StatusRequest();
            inValue.Body = new Client.TP4.StatusRequestBody();
            inValue.Body.id = id;
            Client.TP4.StatusResponse retVal = ((Client.TP4.ThreadPoolSeviceSoap)(this)).Status(inValue);
            return retVal.Body.StatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.TP4.StatusResponse> Client.TP4.ThreadPoolSeviceSoap.StatusAsync(Client.TP4.StatusRequest request) {
            return base.Channel.StatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.TP4.StatusResponse> StatusAsync(long id) {
            Client.TP4.StatusRequest inValue = new Client.TP4.StatusRequest();
            inValue.Body = new Client.TP4.StatusRequestBody();
            inValue.Body.id = id;
            return ((Client.TP4.ThreadPoolSeviceSoap)(this)).StatusAsync(inValue);
        }
    }
}
